import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OPM Productions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="icon" href="/LOGO.svg" sizes="any" />
      <body className={`${inter.className} bg-[#222831] `}>
      <Providers>

        {children}
        </Providers>

      </body>
    </html>
  );
}
